### ISSUE TITLE
optionArgument with defaultValue(true) cannot be set to false

### ISSUE THREAD

**Issue by tomasbjerre** [Softhouse/jargo#29]
When I do:
```
Argument<Boolean> enableLogging = optionArgument("-l", "--enable-logging")
                                    .defaultValue(true).build();
ParsedArguments arg = CommandLineParser.withArguments(enableLogging);
arg.get(enableLogging) //Always true!
```

"enableLogging" cannot be set to false? If I dont supply the argument it will default to true, if I supply it it will be set to true. I must use defaultValue null or false, otherwise there is no way of setting it to false?

Perhaps optionArgument should not have a default value?

**Comment by jontejj** [comment]
In https://github.com/Softhouse/jargo/blob/06b7b4abe0b94c286ac00cd989d36dd141dee8ed/jargo/src/test/java/se/softhouse/jargo/stringparsers/OptionalArgumentTest.java there is a test:

	@Test
	public void testThatOptionalIsFalseWhenArgumentIsGivenAndDefaultIsTrue() throws ArgumentException
	{
		assertThat(optionArgument("--disable-logging").defaultValue(true).parse("--disable-logging")).isFalse();
	}

Perhaps you're passing in the wrong string arguments?

**Comment by tomasbjerre** [comment]
Ok, I'll just use wasGiven, it returns what I would expect get to return.
